// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admin.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_type")
                        .HasComment("тип");

                    b.HasKey("Id", "TypeId")
                        .HasName("pk_cd_entities");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_cd_entities_f_type");

                    b.ToTable("cd_entities", "admin");

                    b.HasComment("сущности");
                });

            modelBuilder.Entity("Domain.Entities.Admin.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_schema")
                        .HasComment("схема");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_table")
                        .HasComment("таблица");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_title")
                        .HasComment("название");

                    b.HasKey("Id")
                        .HasName("pk_cs_entity_types");

                    b.ToTable("cs_entity_types", "admin");

                    b.HasComment("типы сущностей");
                });

            modelBuilder.Entity("Domain.Entities.Admin.Entity", b =>
                {
                    b.HasOne("Domain.Entities.Admin.EntityType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cd_entities_cs_entity_types_f_type");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
